package co.edu.javeriana.zoe.generator.jee7.test;

import co.edu.javeriana.isml.IsmlInjectorProvider;
import co.edu.javeriana.isml.generator.test.TestGeneratorHelper;
import co.edu.javeriana.isml.isml.Controller;
import co.edu.javeriana.isml.isml.InformationSystem;
import co.edu.javeriana.isml.isml.NamedElement;
import co.edu.javeriana.isml.scoping.IsmlModelNavigation;
import co.edu.javeriana.isml.tests.CommonTests;
import co.edu.javeriana.zoe.generator.jee7.templates.ZoeControllerTemplate;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.junit4.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.Test;
import org.junit.runner.RunWith;

@InjectWith(IsmlInjectorProvider.class)
@RunWith(XtextRunner.class)
@SuppressWarnings("all")
public class BackingBeanGeneratorTest extends CommonTests {
  @Inject
  @Extension
  private ParseHelper<InformationSystem> _parseHelper;
  
  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;
  
  @Inject
  @Extension
  private TestGeneratorHelper _testGeneratorHelper;
  
  @Inject
  @Extension
  private IsmlModelNavigation _ismlModelNavigation;
  
  @Inject
  private ZoeControllerTemplate template;
  
  @Test
  public void dataTableGeneration() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\t");
      _builder.append("package test;");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("entity Dieta {");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("String desayuno;");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("String almuerzo;");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("String cena;");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("String merienda;");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("Integer patologia;");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("controller DietaManager {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("has Persistence<Dieta> persistence;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("/**");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* Lists all instances of Dieta.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("*/");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("default listAll() {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("show DietaList(persistence.findAll());");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("/**");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* Lists instances of Dieta.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* @param dietaList The list of instances of Dieta to show.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("*/");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("listDieta(Collection<Dieta> dietaList) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("show DietaList(dietaList);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("createDietaToAdd(Any container, Collection<Dieta> collection) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("show CreateDietaToAdd(container, collection, new Dieta);");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("/**");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* Views an instance of Dieta.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* @param dieta the Dieta to open.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("*/\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("viewDieta(Dieta dieta) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("show ViewDieta(dieta);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("/**");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* Edits an existing instance of Dieta.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* @param dieta the Dieta to open.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("*/\t\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("editDieta(Dieta dieta) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("show EditDieta(dieta);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("/**");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* Creates a a new instance of Dieta.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("*/\t\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("createDieta() {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("show EditDieta(new Dieta);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("/**");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* Saves an instance of Dieta.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* @param dieta the Dieta to save.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("*/\t\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("saveDieta(Dieta dieta) {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("if(persistence.isPersistent(dieta)){");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("persistence.save(dieta);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("} else {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("persistence.create(dieta);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("-> listAll();");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("/**");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* Deletes an instance of Dieta.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("* @param dieta the Dieta to delete.");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("*/\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("deleteDieta(Dieta dieta) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("persistence.remove(dieta);");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("-> listAll();");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("page DietaList(Collection<Dieta> dietaList) controlledBy DietaManager  {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("Form {");
      _builder.newLine();
      _builder.append("\t\t       ");
      _builder.append("Panel(\"Collection<Dieta>\") {");
      _builder.newLine();
      _builder.append("\t\t           ");
      _builder.append("DataTable(\"Collection<Dieta>\", null) {");
      _builder.newLine();
      _builder.append("\t\t               ");
      _builder.append("header : {                    ");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"Desayuno\");");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"Almuerzo\");");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"Cena\");");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"Merienda\");");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"Patologia\");");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"View\");");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"Edit\");");
      _builder.newLine();
      _builder.append("\t\t                   ");
      _builder.append("Label(\"Delete\");");
      _builder.newLine();
      _builder.append("\t\t               ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t               ");
      _builder.append("body : ");
      _builder.newLine();
      _builder.append("\t\t               ");
      _builder.append("for(Dieta dieta in dietaList) {");
      _builder.newLine();
      _builder.append("\t\t               \t\t");
      _builder.append("Label(dieta.desayuno);");
      _builder.newLine();
      _builder.append("\t\t               \t\t");
      _builder.append("Label(dieta.almuerzo);");
      _builder.newLine();
      _builder.append("\t\t               \t\t");
      _builder.append("Label(dieta.cena);");
      _builder.newLine();
      _builder.append("\t\t               \t\t");
      _builder.append("Label(dieta.merienda);");
      _builder.newLine();
      _builder.append("\t\t               \t\t");
      _builder.append("Label(dieta.patologia);");
      _builder.newLine();
      _builder.append("\t\t                   \t");
      _builder.append("Button(\"View\",false)-> viewDieta(dieta);");
      _builder.newLine();
      _builder.append("\t\t                   \t");
      _builder.append("Button(\"Edit\",false) -> editDieta(dieta);");
      _builder.newLine();
      _builder.append("\t\t                   \t");
      _builder.append("Button(\"Delete\",false) -> deleteDieta(dieta);");
      _builder.newLine();
      _builder.append("\t\t               ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t           ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t        \t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("} ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      final InformationSystem obj = this._parseHelper.parse(_builder, this.rs);
      this._validationTestHelper.assertNoErrors(obj);
      EList<NamedElement> _body = obj.getBody();
      NamedElement _head = IterableExtensions.<NamedElement>head(_body);
      co.edu.javeriana.isml.isml.Package _cast = this._ismlModelNavigation.<NamedElement, co.edu.javeriana.isml.isml.Package>cast(_head, co.edu.javeriana.isml.isml.Package.class);
      EList<NamedElement> _body_1 = _cast.getBody();
      NamedElement _get = _body_1.get(2);
      final Controller controller = this._ismlModelNavigation.<NamedElement, Controller>cast(_get, Controller.class);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Entity {");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("name = Person");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("extends = [Animal, Sentient]");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("body = {");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("Attribute {");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("name = name");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("type = String");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("constraints = [Size]");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("Attribute {");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("name = age");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("type = Integer");
      _builder_1.newLine();
      _builder_1.append("\t\t\t");
      _builder_1.append("constraints = []");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      this._testGeneratorHelper.<Controller>assertGenerates(this.template, controller, _builder_1);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
